version: "3"

services:
  app:
    build: BUILD/app/
    image: links
    container_name: links
    restart: always
    volumes: 
        - ./volumes/app:/opt/links
  rp:
    image: nginx:alpine
    container_name: links-rp
    restart: always
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./volumes/rp/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      #- ./volumes/rp/ssl/www.links.int.crt:/etc/ssl/certs/www.links.int.crt:ro
      #- ./volumes/rp/ssl/www.links.int.key:/etc/ssl/private/www.links.int.key:ro
    environment:
      - NGINX_HOST=www.links.int
  ldap:
    build: 
      context: BUILD/ldap/
      args:
        - SAMBA_VERSION=4.15.5
    image: ldap
    container_name: links-ldap
    hostname: ldap
    restart: always
    ports:
      - "389:389"
      - "636:636"
    environment:
      - SAMBA_DC_REALM=links.int
      - SAMBA_DC_DOMAIN=links
      - SAMBA_DC_ADMIN_PASSWD=Password1
      - SAMBA_DC_DNS_BACKEND=SAMBA_INTERNAL
